  jobs:
    increment-git-tag:
      docker:
      - image: cimg/base:current-22.04@sha256:03c91d4730297b5af3718e1e81d43e210eae02be271ed7d370ccb3b994dad2bd
      steps:
        - add_ssh_keys:
            fingerprints:
              - 4c:36:e3:c5:7b:bb:29:da:48:14:53:07:91:bb:98:0d
        - checkout
        - increment-git-tag

    code-scan:
      jobs:
        - codeql/code-scan:
            name: codeql/code-scan python
            context: cambia
            docker-image: cimg/python:3.12
            language: python
