version: 2.1

workflows:
    code-scan:
      jobs:
        - codeql/code-scan:
            name: codeql/code-scan python
            context: cambia
            docker-image: cimg/python:3.13@sha256:87b243ae80d154db75ce5e58af16c72c5dd4b1e23e5c7264a816e85e0c440c13
            language: python

    code-scan-node:
      jobs:
       - codeql/code-scan:
            name: codeql/code-scan node
            context: cambia
            docker-image: cimg/node:18.20@sha256:170f90e441bb5f6135d964addf0ac8da47cf6dff3d59d590b833714c0449ed04
            language: javascript

    code-scan-go:
     jobs:
     - codeql/code-scan:
            name: codeql/code-scan go
            context: cambia
            docker-image: cimg/go:1.23@sha256:172049b3c00117f0f2101b4d8590a3bc98d1fc1ae2e08c410e522e784cc0924f



jobs:
  increment-git-tag:
    docker:
      - image: cimg/base:current-22.04@sha256:03c91d4730297b5af3718e1e81d43e210eae02be271ed7d370ccb3b994dad2bd
