version: 2.1

workflows:
    code-scan:
      jobs:
        - codeql/code-scan:
            name: codeql/code-scan python
            context: cambia
            docker-image: cimg/python:3.12@sha256:24def8371540b4130174d39f1f76600377a0163b58add91249a045789488e80f
            language: python

    code-scan-node:
      jobs:
       - codeql/code-scan:
            name: codeql/code-scan node
            context: cambia
            docker-image: cimg/node:22.12@sha256:0dae71c56fb15a93a8223b5bfe2e93395b97efbf5509a48fe75b890bf1ad0b4e
            language: javascript

    code-scan-go:
     jobs:
     - codeql/code-scan:
            name: codeql/code-scan go
            context: cambia
            docker-image: cimg/go:1.20@sha256:bd1abc34d5deb0c8f55e9f9c8071210e3a5ba9ce874f48a61a390175c2be0da6



jobs:
  increment-git-tag:
    docker:
      - image: cimg/base:current-22.04@sha256:03c91d4730297b5af3718e1e81d43e210eae02be271ed7d370ccb3b994dad2bd
